### ISSUE TITLE
strategie multidb with sqlite3

### ISSUE THREAD

**Issue by henriquensco** [HBN3tw0rk/django-ultratenant#5]

**Comment by lucasrcezimbra** [comment]
Código: https://github.com/HBN3tw0rk/django-ultratenant/blob/c1c3e7e505fe3c04f5b044f548552703fbee8871/tests/test_mapper.py#L13

**Comment by lucasrcezimbra** [comment]
- [ ] Mover [DatabaseMapper](https://github.com/HBN3tw0rk/django-ultratenant/blob/c1c3e7e505fe3c04f5b044f548552703fbee8871/tests/test_mapper.py#L13) para https://github.com/HBN3tw0rk/django-ultratenant/blob/main/ultratenant/multidb.py
