### ISSUE TITLE
Path: url.com/tenant

### ISSUE THREAD

**Issue by henriquensco** [HBN3tw0rk/django-ultratenant#6]

**Comment by CleitonDeLima** [comment]
Tem alguma coisa em mente para fazer essa issue?

**Comment by lucasrcezimbra** [comment]
Essa task foi resolvida no #33 
Código: https://github.com/HBN3tw0rk/django-ultratenant/blob/b1e5334793acd1b0972e93f2d93db9b005c27f0d/ultratenant/middlewares.py#L31
